//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanFlashInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanFlashInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap flashLogo {
            get {
                object obj = ResourceManager.GetObject("flashLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Control Panel\Extended Properties\System.ControlPanel.Category]
        ///&quot;${SYSTEM_32_PATH}\\FlashPlayerCPLApp.cpl&quot;=dword:0000000a
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FlashPlayerApp.exe]
        ///&quot;DisableExceptionChainValidation&quot;=dword:00000000
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\Clean Flash Player]
        ///&quot;DisplayName&quot;=&quot;Clean Flash Player ${VERSION}&quot;
        ///&quot;HelpLink&quot;=&quot;https://clean [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string installGeneral {
            get {
                return ResourceManager.GetString("installGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Control Panel\Extended Properties\System.ControlPanel.Category]
        ///&quot;${SYSTEM_32_PATH}\\FlashPlayerCPLApp.cpl&quot;=dword:0000000a
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\FlashPlayerApp.exe]
        ///&quot;DisableExceptionChainValidation&quot;=dword:00000000 的本地化字符串。
        /// </summary>
        internal static string installGeneral64 {
            get {
                return ResourceManager.GetString("installGeneral64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [HKEY_LOCAL_MACHINE\Software\Macromedia\FlashPlayerPlugin]
        ///&quot;isPartner&quot;=dword:00000001
        ///&quot;Version&quot;=&quot;${VERSION}&quot;
        ///&quot;PlayerPath&quot;=&quot;${FLASH_64_PATH}\\NPSWF_${VERSION_PATH}.dll&quot;
        ///&quot;UninstallerPath&quot;=-
        ///&quot;isScriptDebugger&quot;=dword:00000000
        ///&quot;isESR&quot;=dword:00000000
        ///&quot;isMSI&quot;=dword:00000000
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Macromedia\FlashPlayerPluginReleaseType]
        ///&quot;Release&quot;=dword:00000001
        ///
        ///[HKEY_LOCAL_MACHINE\Software\MozillaPlugins\@adobe.com/FlashPlayer]
        ///&quot;Vendor&quot;=&quot;Adobe&quot;
        ///&quot;ProductName&quot;=&quot;Adobe® Flash® Player ${VERSION} Plugin&quot;
        ///&quot;Path&quot;= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string installNP {
            get {
                return ResourceManager.GetString("installNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [HKEY_LOCAL_MACHINE\Software\Wow6432Node\Macromedia\FlashPlayerPlugin]
        ///&quot;PlayerPath&quot;=&quot;${FLASH_32_PATH}\\NPSWF_${VERSION_PATH}.dll&quot;
        ///&quot;Version&quot;=&quot;${VERSION}&quot;
        ///&quot;UninstallerPath&quot;=-
        ///&quot;isScriptDebugger&quot;=dword:00000000
        ///&quot;isESR&quot;=dword:00000000
        ///&quot;isMSI&quot;=dword:00000000
        ///&quot;isPartner&quot;=dword:00000001
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Macromedia\FlashPlayerPluginReleaseType]
        ///&quot;Release&quot;=dword:00000001
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Wow6432Node\MozillaPlugins\@adobe.com/FlashPlayer]
        ///&quot;ProductName&quot;=&quot;Adobe® Flash® Player ${VERSI [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string installNP64 {
            get {
                return ResourceManager.GetString("installNP64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [HKEY_LOCAL_MACHINE\Software\Classes\.mfp]
        ///&quot;Content Type&quot;=&quot;application/x-shockwave-flash&quot;
        ///@=&quot;MacromediaFlashPaper.MacromediaFlashPaper&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Classes\.sol]
        ///&quot;Content Type&quot;=&quot;text/plain&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Classes\.sor]
        ///&quot;Content Type&quot;=&quot;text/plain&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Classes\.spl]
        ///&quot;Content Type&quot;=&quot;application/futuresplash&quot;
        ///@=&quot;ShockwaveFlash.ShockwaveFlash&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Classes\.swf]
        ///&quot;Content Type&quot;=&quot;application/x-shockwave-flash&quot;
        ///@=&quot;ShockwaveFlash.Sho [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string installOCX {
            get {
                return ResourceManager.GetString("installOCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [HKEY_LOCAL_MACHINE\Software\Wow6432Node\Macromedia\FlashPlayer]
        ///&quot;CurrentVersion&quot;=&quot;${VERSION_COMMA}&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Macromedia\FlashPlayer\SafeVersions]
        ///&quot;28.0&quot;=dword:ffffffff
        ///&quot;27.0&quot;=dword:ffffffff
        ///&quot;26.0&quot;=dword:ffffffff
        ///&quot;21.0&quot;=dword:ffffffff
        ///&quot;24.0&quot;=dword:ffffffff
        ///&quot;7.0&quot;=dword:ffffffff
        ///&quot;6.0&quot;=dword:ffffffff
        ///&quot;30.0&quot;=dword:ffffffff
        ///&quot;29.0&quot;=dword:000000ab
        ///&quot;31.0&quot;=dword:ffffffff
        ///&quot;32.0&quot;=dword:ffffffff
        ///&quot;8.0&quot;=dword:ffffffff
        ///&quot;11.0&quot;=dword:ffffffff
        ///&quot;10.0&quot;=dword:ffffffff
        ///&quot;13.0&quot;=dword:ffffffff
        ///&quot;12.0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string installOCX64 {
            get {
                return ResourceManager.GetString("installOCX64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [HKEY_LOCAL_MACHINE\Software\Macromedia\FlashPlayerPepper]
        ///&quot;UninstallerPath&quot;=-
        ///&quot;PlayerPath&quot;=&quot;${FLASH_64_PATH}\\pepflashplayer_${VERSION_PATH}.dll&quot;
        ///&quot;isScriptDebugger&quot;=dword:00000000
        ///&quot;isESR&quot;=dword:00000000
        ///&quot;isMSI&quot;=dword:00000000
        ///&quot;isPartner&quot;=dword:00000001
        ///&quot;Version&quot;=&quot;${VERSION}&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Macromedia\FlashPlayerPepperReleaseType]
        ///&quot;Release&quot;=dword:00000001 的本地化字符串。
        /// </summary>
        internal static string installPP {
            get {
                return ResourceManager.GetString("installPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [HKEY_LOCAL_MACHINE\Software\Wow6432Node\Macromedia\FlashPlayerPepper]
        ///&quot;UninstallerPath&quot;=-
        ///&quot;PlayerPath&quot;=&quot;${FLASH_32_PATH}\\pepflashplayer_${VERSION_PATH}.dll&quot;
        ///&quot;isScriptDebugger&quot;=dword:00000000
        ///&quot;isESR&quot;=dword:00000000
        ///&quot;isMSI&quot;=dword:00000000
        ///&quot;isPartner&quot;=dword:00000001
        ///&quot;Version&quot;=&quot;${VERSION}&quot;
        ///
        ///[HKEY_LOCAL_MACHINE\Software\Wow6432Node\Macromedia\FlashPlayerPepperReleaseType]
        ///&quot;Release&quot;=dword:00000001 的本地化字符串。
        /// </summary>
        internal static string installPP64 {
            get {
                return ResourceManager.GetString("installPP64", resourceCulture);
            }
        }
    }
}
